# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a98d588a7652c210648739e9af79f48a2feb6c1e18da984f772c8dee480af91913c251abc3d366778a99a8392109897a323e736495685fab2f613f2a3154260

test:
  secret_key_base: 0dd8c34450ce80db9be9f7b18077a8d57ecdd64a61ac442a31c958dc3228c45f99c43a87c4ff4fb4a30be630543d2eb5f17904972d034f8d540816214ed2ef91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
